version: '2'
services:
  elasticsearch:
    user: 1009:999
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - './elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx1000m -Xms1000m'
    networks:
      - elk
    restart: always
  logstash:
    user: 1009:999
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro'
      - './logstash/pipeline:/usr/share/logstash/pipeline:ro'
    ports:
      - '5000:5000'
      - '5000:5000/udp'
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: '-Xmx256m -Xms256m'
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    user: 1009:999
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - './kibana/config/:/usr/share/kibana/config:ro'
    ports:
      - '5601:5601'
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge
