ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}
USER docker

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
